### PR TITLE
Move funflow package to top-level

### PR DESCRIPTION
**Pull request by mboes**
The overarching reason is this: the funflow dir really does need
a README at its root. Previously it did not, because the README was at
repo top-level. But this causes problems. In particular, it means the
funflow dir is no longer self-contained. More importantly, you can't
include the README in package sdists uploaded to Hackage.

With funflow at top-level, we have top-level README, which is also the
funflow readme. This is natural because the top-level README is about
the top-level package, aka funflow.

### CODE REVIEW

**Comment by glutamate** [comment]
Can't we just symlink the README?

**Comment by mboes** [comment]
Won't work. Sdist will just include a symlink. Also, GitHub display won't
work as expected. More confusion than it's worth.

**Comment by nc6** [comment]
I really don't like this design. It makes the top level of the repo harder to navigate. I'd much rather just have a second, shorter readme in the funflow directory and link to this one for more detailed examples.

**Comment by mboes** [comment]
> It makes the top level of the repo harder to navigate.

Harder than for any other (singleton) package? Is it the presence of sub-packages that make this unintuitive? If so, would putting them in a dedicated subdir, much in the style of a `vendor` dir containing lots of checked-in dependencies, help?

There's a tension between having all packages at the same level (assuming that's desirable), and presenting all compelling information upfront. If the top-level README is just a ToC to other README's, that introduces an extra level of indirection for impatient new potential users landing on the GitHub front page. If it has useful information, then clearly that information should be part of the package-specific README too, but then we're just duplicating...

A top-level ToC README might be the lesser evil, but I really don't think it's ideal.

**Comment by glutamate** [comment]
I agree with Nick. This isn't the canonical way of laying out a multi-cabal package repo.

Not sure what to do about it.

**Comment by mboes** [comment]
I'm not sure there is a *canonical* way.

I'm okay with any other repo organization but let's please not close #68 without *every* package having a proper README. These README's should be part of the tarballs uploaded to Hackage, and should be informative.

**Comment by nc6** [comment]
Opened #72 which should resolve this.

**Pull request closed without merging**
