### PR TITLE
fixed. renamePath:rename: permission denied

### PR DESCRIPTION
**Pull request by Lupino**

### CODE REVIEW

**Comment by nc6** [comment]
Hi! Thanks for the contribution to funflow. Would you mind explaining a little more what problem this is fixing for you? We've never seen issues with permission denied in this case, so it would be good to work out what this is addressing.

**Comment by Lupino** [comment]
```haskell
{-# LANGUAGE Arrows #-}
{-# LANGUAGE QuasiQuotes #-}
import Control.Arrow
import Control.FunFlow
import Control.FunFlow.Exec.Simple (withSimpleLocalRunner)
import Data.Default
import Path

-- | Flow which asks for the user's name, then their favourite number.
--   The favourite number will be cached, such that if the user comes back,
--   they will not be asked again.
favouriteNumber :: SimpleFlow () (String, String)
favouriteNumber = proc () -> do
  name <- stepIO (\_ -> putStrLn "Hi, what's your name?" >> getLine) -< ()
  -- We enable caching for this step. The default cacher uses 'Store' instances
  -- to provide serialisation/deserialisation. The ident is used to ensure that
  -- multiple different steps with the same input do not resolve to the same
  -- cache item.
  fnum <- stepIO' (def { cache = defaultCacherWithIdent 172652 })
                  (\_ -> putStrLn "What's your favourite number?" >> getLine) -< name
  returnA -< (name, fnum)

-- | Runs the 'favourite number' flow in IO.
runFavouriteNumber :: IO ()
runFavouriteNumber = do
  -- Use /tmp/funflow as the path to our content store.
  res <- withSimpleLocalRunner [absdir|/Users/lmj/yuntan/experiment/funflow/tmp|] $ \run ->
    -- 'run' takes the flow and the initial input. Since this flow has an input type of '()',
    -- this is what we provide.
    run favouriteNumber ()
  case res of
    Left err -> putStrLn $ "Something went wrong: " ++ show err
    Right (name, num) -> putStrLn $ "Hi, " ++ name ++ ", your favourite number is " ++ num

main :: IO ()
main = runFavouriteNumber
```

**Comment by aherrmann** [comment]
Hi @Lupino, thanks for providing the code.
Could you also post the output of the following command `ls -ld /tmp`? I'm suspecting that the error is caused by the sticky bit being set on `/tmp`. 

Does the error persist if you use a different store root? I.e. if you replace `/tmp` in `[absdir|/tmp|]` by `/tmp/funflow` or some path in your home directory?

Just to be sure, have you confirmed that it works without error after your proposed change?

**Comment by Lupino** [comment]
screen shot 2018-01-12 at 12 20 40 pm

this is my real path. 

```haskell 
520 -- | Mark a pending item as complete.
521 markComplete :: ContentStore -> ContentHash -> IO Item
522 markComplete store inHash = withStoreLock store $
523   internalQuery store inHash >>= \case
524     Missing () -> throwIO (NotPending inHash)
525     Complete _ -> throwIO (AlreadyComplete inHash)
526     Pending build -> withWritableStore store $ do
527       unsetWritableRecursively build
528       do
529         let metadataDir = mkMetadataDirPath store inHash
530         exists <- doesDirExist metadataDir
531         when exists $
532           unsetWritableRecursively metadataDir
533       -- XXX: Hashing large data can take some time,
534       --   could we avoid locking the store for all that time?
535       outHash <- contentHash (DirectoryContent build)
536       let out = mkItemPath store outHash
537           link' = mkCompletePath store inHash
538       doesDirExist out >>= \case
539         True -> removePathForcibly (fromAbsDir build)
540         False -> renameDir build out
541       rel <- makeRelative (parent link') out
542       let from' = dropTrailingPathSeparator $ fromAbsDir link'
543           to' = dropTrailingPathSeparator $ fromRelDir rel
544       createSymbolicLink to' from'
545       addBackReference store inHash (Item outHash)
546       pure $! Item outHash
```

when `unsetWritableRecursively build` 
the build directory is `read only`
 
so build direcoory can't remove and rename:  ` renameDir build out` or `removePathForcibly (fromAbsDir build)`

**Comment by aherrmann** [comment]
@Lupino Thanks for clarifying.

> when `unsetWritableRecursively build` the build directory is `read only`
> so build direcoory can't remove and rename: `renameDir build out`

I've had a closer look and there seems to be a subtle difference between Linux and macOS (which I'm guessing you're testing this on).
Removing/renaming a file only requires write permissions on the containing directory, not on the file itself.
On Linux, renaming a directory within the same parent directory only requires write permissions on the parent directory, not on the renamed directory itself;
moving a directory from one parent directory to another also requires write permissions on the moved directory itself (to change the `..` entry).
It seems that on macOS renaming a directory always requires write permissions on the renamed directory itself.


A completed item should not be changed anymore. We're setting these to read-only to prevent accidental modification. Could you also change [line 539](https://github.com/tweag/funflow/pull/51/files#diff-06fe0eceda2b774b025d64b91b0c4f0cR539) to  preserve this behaviour? E.g.

```
False -> do
  renameDir build out
  unsetWritableRecursively out
```

**Comment by Lupino** [comment]
@aherrmann changed.

**Pull request merged**
